### ISSUE TITLE
Crashed on startup when networks is disable

### ISSUE THREAD

**Issue by DeadNumbers** [go-telegram-bot-api/telegram-bot-api#113]
1) Disable your WiFi|Ethernet
2) Run your application
3) ->
```
Post https://api.telegram.org/***/getMe: dial tcp: lookup api.telegram.org: no such host
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x5cb146]

goroutine 21 [running]:
net/http.(*Client).deadline(0x0, 0xc4200e8030, 0x410132, 0xc4200e2250)
	/usr/lib/go/src/net/http/client.go:186 +0x26
net/http.(*Client).Do(0x0, 0xc420106100, 0xc, 0x6a99f3, 0x21)
	/usr/lib/go/src/net/http/client.go:497 +0x89
net/http.(*Client).Post(0x0, 0xc4200dc510, 0x27, 0x6a99f3, 0x21, 0x7b0340, 0xc4200e01e0, 0x90, 0xc4200dc510, 0x27)
	/usr/lib/go/src/net/http/client.go:720 +0xf8
net/http.(*Client).PostForm(0x0, 0xc4200dc510, 0x27, 0xc4200dc4e0, 0x2, 0xc4200dc510, 0x27)
	/usr/lib/go/src/net/http/client.go:752 +0xdd
gopkg.in/telegram-bot-api%2ev4.(*BotAPI).MakeRequest(0xc4200de360, 0x6a25f3, 0xa, 0xc4200dc4e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/user/go/src/gopkg.in/telegram-bot-api.v4/bot.go:60 +0x193
gopkg.in/telegram-bot-api%2ev4.(*BotAPI).GetUpdates(0xc4200de360, 0x0, 0x0, 0x1e, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/user/go/src/gopkg.in/telegram-bot-api.v4/bot.go:386 +0xc8
gopkg.in/telegram-bot-api%2ev4.(*BotAPI).GetUpdatesChan.func1(0xc4200de360, 0xc4200e01a0, 0xc4200de3c0)
	/home/user/go/src/gopkg.in/telegram-bot-api.v4/bot.go:456 +0x65
created by gopkg.in/telegram-bot-api%2ev4.(*BotAPI).GetUpdatesChan
	/home/user/go/src/gopkg.in/telegram-bot-api.v4/bot.go:472 +0xa9
```

I have no errors if disabling networks after application run. So, can you fix request looping to server?

**Comment by zhulik** [comment]
What behavior do you want to see? Program panics because it doesn't know what to do when the network is down. If you want to loop just recover the panic

**Comment by DeadNumbers** [comment]
@zhulik Connect in a loop until the network appears.

**Comment by zhulik** [comment]
@DeadNumbers you can easily implemet it by yourself: recover the panic and run your code again. Built-in recover in the library will hide the error from application developer and make development proccess more confusing. Actually if you disable the network while your programm is running and try to make any request, you will see the same behavior: program will panic. It is ok behaviour because error handling is a task for application developer, not the library

**Comment by zhuharev** [comment]
Have you dealt with your problem?
