### ISSUE TITLE
Sending a message via gorutin

### ISSUE THREAD

**Issue by asuleymanov** [go-telegram-bot-api/telegram-bot-api#124]
Greetings.
There is a code:
`package main

import (
	"log"
	"strconv"
	"time"

	"github.com/asuleymanov/telegram-bot-api"
)

var (
	bot   *tgbotapi.BotAPI
	reply string
)

func main() {
	bot, err := tgbotapi.NewBotAPI("33....")
	log.Println("Start Bot")
	if err != nil {
		log.Panic(err)
	}
	bot.Debug = true

	u := tgbotapi.NewUpdate(0)
	u.Timeout = 60
	updates, _ := bot.GetUpdatesChan(u)
	time.Sleep(time.Millisecond * 500)
	updates.Clear()

	go send()

	for update := range updates {
		if update.Message == nil {
			continue
		}
	}
}

func send() {
	i := 0
	for {
		reply = "Test " + strconv.Itoa(i)
		msg := tgbotapi.NewMessage(int64(2233....), reply)
		bot.Send(msg)
		i++
		time.Sleep(10 * time.Second)
	}
}
`
An error occurs during execution:
`2017/09/28 15:03:23 Start Bot
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6086ad]

goroutine 51 [running]:
github.com/asuleymanov/telegram-bot-api.(*BotAPI).MakeRequest(0x0, 0x69ebb0, 0xb, 0xc42011c030, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ubuntu/workspace/src/github.com/asuleymanov/telegram-bot-api/bot.go:62 +0xbd
github.com/asuleymanov/telegram-bot-api.(*BotAPI).makeMessageRequest(0x0, 0x69ebb0, 0xb, 0xc42011c030, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ubuntu/workspace/src/github.com/asuleymanov/telegram-bot-api/bot.go:99 +0xb3
github.com/asuleymanov/telegram-bot-api.(*BotAPI).sendChattable(0x0, 0x7cb820, 0xc420114060, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ubuntu/workspace/src/github.com/asuleymanov/telegram-bot-api/bot.go:323 +0x114
github.com/asuleymanov/telegram-bot-api.(*BotAPI).Send(0x0, 0x7cb820, 0xc420114060, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ubuntu/workspace/src/github.com/asuleymanov/telegram-bot-api/bot.go:254 +0xbf
main.send()
        /home/ubuntu/workspace/src/bt/bt.go:44 +0x15b
created by main.main
        /home/ubuntu/workspace/src/bt/bt.go:30 +0x16e
exit status 2`
Could you explain why this error occurs? And how do I fix this?

**Comment by asuleymanov** [comment]
Сам спросил сам решил. 
```
package main

import (
	"log"
	"strconv"
	"time"

	"github.com/asuleymanov/telegram-bot-api"
)

var (
	bot   *tgbotapi.BotAPI
	reply string
	err   error
)

func main() {
	bot, err = tgbotapi.NewBotAPI("33.....c")
	log.Println("Start Bot")
	if err != nil {
		log.Panic(err)
	}
	bot.Debug = true

	u := tgbotapi.NewUpdate(0)
	u.Timeout = 60
	updates, err := bot.GetUpdatesChan(u)
	if err != nil {
		log.Println(err)
	}
	time.Sleep(time.Millisecond * 500)
	updates.Clear()

	go send()

	for update := range updates {
		if update.Message == nil {
			continue
		}
	}
}

func send() {
	i := 0
	for {
		reply = "Test " + strconv.Itoa(i)
		msg := tgbotapi.NewMessage(int64(22.....), reply)
		bot.Send(msg)
		i++
		time.Sleep(10 * time.Second)
	}
}

```
