### ISSUE TITLE
Runtime error after editing the message

### ISSUE THREAD

**Issue by zikle** [go-telegram-bot-api/telegram-bot-api#160]
I have this code: https://gist.github.com/zikle/038e8ac05e7da0adff61431d80d688db

Everything works well, but when I edit the sent message I get runtime error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6453d1]

goroutine 32 [running]:
main.main.func1(0xc42011c1e0, 0xc4200fc080)
	/home/user/go/s.go:28 +0x51
created by main.main
	/home/user/go/s.go:26 +0x26c
exit status 2
```

What am I doing wrong? Thank you in advance.

PS English is not my native language 
PSS These is my first bot

**Comment by zikle** [comment]
I found my mistake, i just forgot to add
```
if update.Message == nil {
    continue
}
```
Thanks to everyone
