### ISSUE TITLE
Panic when creating bot api

### ISSUE THREAD

**Issue by bosix** [go-telegram-bot-api/telegram-bot-api#372]
I'm a bit confused because I was using this repo for several months and now my program panics when initializing the bot.

The following code is executed when my app is started:

```golang
package helper

import (
	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api"
	"log"
	"os"
	"strconv"
)

var bot *tgbotapi.BotAPI
var chatID int64

func init() {
	var err error
	bot, err = tgbotapi.NewBotAPI(os.Getenv("TELEGRAM_BOT_API_KEY"))
	if err != nil {
		log.Panic(err)
	}

	chatIDInt, _ := strconv.Atoi(os.Getenv("TELEGRAM_BOT_CHANNEL_ID"))
	chatID = int64(chatIDInt)
}

// ...
```

The app throws a panic because `tgbotapi.NewBotAPI` returns an error:

```
2020/09/25 20:41:37 Not Found
panic: Not Found

goroutine 1 [running]:
log.Panic(0xc0001e3f08, 0x1, 0x1)
        /usr/lib/go-1.15/src/log/log.go:351 +0xae
my-app/helper.init.1()
        /home/bosi/go/src/my-app/helper/telegram.go:17 +0x10a
exit status 2
```

Both env vars are set. Does anyone have an idea where the mistake is?

**Comment by bosix** [comment]
Well...it was kind of a layer 8 problem. After digging into the package I found out that the env file I use to load config looks like the following:

```
TELEGRAM_BOT_API_KEY="mytoken"
TELEGRAM_BOT_CHANNEL_ID=mychatid
```

The quotes you see at the first param are passed straight through this package and cause an error because they also appear in the url.
