### ISSUE TITLE
Panic when sending Photo by URL

### ISSUE THREAD

**Issue by teamalpha5441** [go-telegram-bot-api/telegram-bot-api#74]
Trying to send a Photo by URL results in nil pointer dereference

This is the panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x476208]

goroutine 52 [running]:
panic(0x6224a0, 0xc42000c0d0)
        /usr/lib/go/src/runtime/panic.go:500 +0x1a1
io.(*multiReader).Read(0xc42023c1a0, 0xc4204572e7, 0x44, 0xd19, 0x1cc, 0x0, 0x0)
        /usr/lib/go/src/io/multi.go:20 +0x98
io/ioutil.(*nopCloser).Read(0xc42022a270, 0xc4204572e7, 0x44, 0xd19, 0x1cc, 0x0, 0x0)
        <autogenerated>:4 +0x6b
io.(*LimitedReader).Read(0xc420376640, 0xc4204572e7, 0xd19, 0xd19, 0x1cc, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:436 +0x6c
bufio.(*Writer).ReadFrom(0xc420322f80, 0x75f9e0, 0xc420376640, 0xc4200fcbb8, 0x1, 0x18)
        /usr/lib/go/src/bufio/bufio.go:693 +0xcc
io.copyBuffer(0x75f660, 0xc420322f80, 0x75f9e0, 0xc420376640, 0x0, 0x0, 0x0, 0x631bc0, 0x1, 0xc420376640)
        /usr/lib/go/src/io/io.go:384 +0x323
io.Copy(0x75f660, 0xc420322f80, 0x75f9e0, 0xc420376640, 0xf, 0xc420379100, 0x581d02)
        /usr/lib/go/src/io/io.go:360 +0x68
net/http.(*transferWriter).WriteBody(0xc4202fa7e0, 0x75f660, 0xc420322f80, 0x2, 0x2)
        /usr/lib/go/src/net/http/transfer.go:227 +0x677
net/http.(*Request).write(0xc4200c01e0, 0x75f660, 0xc420322f80, 0x0, 0xc420365890, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/http/request.go:565 +0x778
net/http.(*persistConn).writeLoop(0xc420474300)
        /usr/lib/go/src/net/http/transport.go:1649 +0x1ac
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/net/http/transport.go:1063 +0x50e
exit status 2
```

This is my code:

```
package main

import (
        "log"
        "github.com/go-telegram-bot-api/telegram-bot-api"
        "net/url"
)

func main() {
        bot, err := tgbotapi.NewBotAPI("pls enter some token here")
        if err != nil {
                log.Panic(err)
        }
        bot.Debug = true
        log.Printf("Authorized on account %s", bot.Self.UserName)

        u := tgbotapi.NewUpdate(0)
        u.Timeout = 60
        updates, err := bot.GetUpdatesChan(u)

        url_ptr, _ := url.Parse("https://assets-cdn.github.com/images/modules/site/home-ill-platform.png")
        url := *url_ptr

        for update := range updates {
                if update.Message == nil {
                        continue
                }
                log.Printf("[%s] %s", update.Message.From.UserName, update.Message.Text)
                msg := tgbotapi.NewPhotoUpload(update.Message.Chat.ID, url)
                bot.Send(msg);
        }
}
```

The panic is caused by this line:
https://github.com/go-telegram-bot-api/telegram-bot-api/blob/99170e2de436c1be90d2ef23dcf533b55a973e56/bot.go#L171

The panic only happens when sending a Photo via URL, if NewPhotoUpload is called with file path, no panic happens and the Photo is sent correctly.

**Comment by Syfaro** [comment]
```go
url_ptr, _ := url.Parse("https://assets-cdn.github.com/images/modules/site/home-ill-platform.png")
url := *url_ptr
```

Why are you passing it the address of a `url.URL` instead of just the actual `url.URL`?

**Comment by teamalpha5441** [comment]
I am passing the actual object, just had to get the actual url.URL by dereferencing the pointer returned by url.Parse

**Comment by Hamper** [comment]
Same error, change https://github.com/go-telegram-bot-api/telegram-bot-api/blob/13c54dc548f7ca692fe434d4b7cac072b0de0e0b/bot.go#L161 from `url.URL` to `*url.URL` and direct use result of url.Parse does not help.

**Comment by Hamper** [comment]
This works:
```go
msg := tgbotapi.NewPhotoUpload(update.Message.Chat.ID, nil)
msg.FileID = "http://.../..png"
msg.UseExisting = true
```

**Comment by zhuharev** [comment]
@teamalpha5441 have you dealt with your problem?

**Comment by teamalpha5441** [comment]
Yes, I replaced this

**Comment by L11R** [comment]
Why this issue is closed? Bug still actual for the latest version.

**Comment by tetafro** [comment]
> This works:
> 
> ```go
> msg := tgbotapi.NewPhotoUpload(update.Message.Chat.ID, nil)
> msg.FileID = "http://.../..png"
> msg.UseExisting = true
> ```

Just use [NewPhotoShare](https://github.com/go-telegram-bot-api/telegram-bot-api/blob/master/helpers.go#L70-L83)

```go
msg := tg.NewPhotoShare(chatID, "https://example.com/image.png")
_, err := api.Send(msg)
```

**Comment by yb172** [comment]
> > This works:
> > ```go
> > msg := tgbotapi.NewPhotoUpload(update.Message.Chat.ID, nil)
> > msg.FileID = "http://.../..png"
> > msg.UseExisting = true
> > ```
> 
> Just use [NewPhotoShare](https://github.com/go-telegram-bot-api/telegram-bot-api/blob/master/helpers.go#L70-L83)
> 
> ```go
> msg := tg.NewPhotoShare(chatID, "https://example.com/image.png")
> _, err := api.Send(msg)
> ```

This does a different thing - it uses the file already uploaded. To get file uploaded you have touse `NewPhotoUpload` which fails if URL is passed

**Comment by safonovmm** [comment]
If anybody interested, the workaround that worked for me is using MediaGroupConfig with slice of InputMediaPhoto, consisting of only one element like so:
``` go	
	inputMedia := make([]interface{}, 0)
	imp := tgbotapi.NewInputMediaPhoto("https://.../image.png")
	imp.Caption = "caption"
	inputMedia = append(inputMedia, imp)
	_, err := t.bAPI.Send(tgbotapi.MediaGroupConfig{InputMedia: inputMedia})
```
